model:
  type: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42

data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  train_data_path: "data/processed/train_matches.csv"
  test_data_path: "data/processed/test_matches.csv"
  match_info_path: "data/processed/match_info.csv"
  player_info_path: "data/processed/player_info.csv"

training:
  test_size: 0.2
  split_method: "temporal"  # temporal split (chronological) to avoid data leakage
  split_date: "2020-02-20"  # matches before this date are training, after are test
  random_state: 42
  epochs: 50

prediction:
  match_analysis_threshold: 0.5
  win_probability_output: true